---
# Step 1: AWS DNS + Security Groups from control node (delegated)
- hosts: ansible_test
  gather_facts: false
  tasks:
    - import_role:
        name: dns_and_sg
      delegate_to: localhost
      run_once: true
      vars:
        aws_region: us-east-1
        route53_zone: avsdevops.com.
        route53_record: chat.avsdevops.com.
        route53_record_type: A
        route53_ttl: 300
        security_group_ids:
          - sg-0b79ee8160854fcee
          - sg-001d93a7e6c36189b
        ec2_instance_ips:
          - 13.222.54.88
          - 3.92.209.217
          - 13.221.179.41

# Step 2: Deploy Python/Flask app + Configure Nginx+SSL
- hosts: ansible_test
  become: yes
  vars:
    domain_name: chat.avsdevops.com
    flask_port: 5000
    pplx_api_key: "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"
  roles:
    - python_env
    - app
    - nginx_ssl
